db:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  name: ${DB_NAME:cook-book}
  user: ${DB_USER:cook-book}
  pass: ${DB_PASS:cook-book}

logging:
  level:
    root: INFO
    dev.akif.cookbook: DEBUG

spring:
  flyway:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    user: ${db.user}
    password: ${db.pass}

  r2dbc:
    url: r2dbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.user}
    password: ${db.pass}
